### ISSUE TITLE
DBSCANKdtreeCluster 经过处理后，聚类点云的坐标方向发生了改变

### ISSUE THREAD

**Issue by robbie2021** [JaminJiang/dbscan_kdtree#3]
您好！非常感谢您的开源代码。我在使用的过程中，发现点云经过DBSCANKdtreeCluster聚类方式处理后，聚类出的点云的坐标方向发生了改变，请问是什么原因呢？
![11](https://user-images.githubusercontent.com/17980437/225566770-188bd7cc-83de-4732-a1fa-9f72afa7a9bb.png)
![22](https://user-images.githubusercontent.com/17980437/225566784-c04d6853-8c8e-48bc-b897-068b0a651c4c.png)

**Comment by JaminJiang** [comment]
这个需要您自己细心排查了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月16日(周四) 下午5:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [JaminJiang/dbscan_kdtree] DBSCANKdtreeCluster 经过处理后，聚类点云的坐标方向发生了改变 (Issue #3)




 
您好！非常感谢您的开源代码。我在使用的过程中，发现点云经过DBSCANKdtreeCluster聚类方式处理后，聚类出的点云的坐标方向发生了改变，请问是什么原因呢？

**Comment by robbie2021** [comment]
好的，问题已找到~
